/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AppRouteImport } from "./routes/app";
import { Route as AuthRouteImport } from "./routes/auth";
import { Route as ChatRouteImport } from "./routes/chat";
import { Route as AppIndexRouteImport } from "./routes/app.index";
import { Route as AppDiagnosticRouteImport } from "./routes/app.diagnostic";
import { Route as AppPlansRouteImport } from "./routes/app.plans";
import { Route as AppRedsRouteImport } from "./routes/app.reds";
import { Route as AppTeacherRouteImport } from "./routes/app.teacher";
import { Route as ChatIndexRouteImport } from "./routes/chat.index";
import { Route as ChatConversationIdRouteImport } from "./routes/chat.$conversationId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const AppRoute = AppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
});
const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
});
const ChatRoute = ChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
});
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
});
const AppDiagnosticRoute = AppDiagnosticRouteImport.update({
  id: "/diagnostic",
  path: "/diagnostic",
  getParentRoute: () => AppRoute,
});
const AppPlansRoute = AppPlansRouteImport.update({
  id: "/plans",
  path: "/plans",
  getParentRoute: () => AppRoute,
});
const AppRedsRoute = AppRedsRouteImport.update({
  id: "/reds",
  path: "/reds",
  getParentRoute: () => AppRoute,
});
const AppTeacherRoute = AppTeacherRouteImport.update({
  id: "/teacher",
  path: "/teacher",
  getParentRoute: () => AppRoute,
});
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ChatRoute,
});
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: "/$conversationId",
  path: "/$conversationId",
  getParentRoute: () => ChatRoute,
});

const AppRouteChildren = {
  AppDiagnosticRoute: AppDiagnosticRoute,
  AppPlansRoute: AppPlansRoute,
  AppRedsRoute: AppRedsRoute,
  AppTeacherRoute: AppTeacherRoute,
  AppIndexRoute: AppIndexRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const ChatRouteChildren = {
  ChatConversationIdRoute: ChatConversationIdRoute,
  ChatIndexRoute: ChatIndexRoute,
};

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren);

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRouteWithChildren,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren);
